CREATE TABLE department (
	department_id BIGSERIAL PRIMARY KEY,
	department_code VARCHAR(20) NOT NULL UNIQUE,
	department_name VARCHAR(100) NOT NULL,
	display_order INTEGER NOT NULL DEFAULT 0,
	deleted_flg BOOLEAN NOT NULL DEFAULT FALSE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
