########################################
# Application
########################################

spring.application.name=practical-app-starter

########################################
# Database (PostgreSQL)
########################################

spring.datasource.url=jdbc:postgresql://localhost:5432/practical_app_starter
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

########################################
# MyBatis Settings
########################################

mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=io.github.ysmkotm.practicalappstarter.entity,io.github.ysmkotm.practicalappstarter.dto

########################################
# Logging（開発用設定）
########################################

logging.level.io.github.ysmkotm.practicalappstarter=DEBUG
logging.level.org.mybatis=DEBUG

# SQLログを表示する場合は有効化
# mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

########################################
# Thymeleaf（開発用設定）
########################################

spring.thymeleaf.cache=false
